### ISSUE TITLE
query "where" doesn't work with repl

### ISSUE THREAD

**Issue by Hoxolotl** [muze-nl/jaqt#6]
When using repl:

```javascript
> result = from(data.people).where({ gender: "male"}).select({ name: _ })
Proxy [ [], { get: [Function: get] } ]
> JSON.stringify(result)
'[]'
```

**Comment by poef** [comment]
The repl is doing something weird here, if you write the code and run it using node, without the repl, it just works. I'm not diving into the repl to try and figure out what is going on. Instead I plan to write a simple webpage that you can start with `npm run dev` or something similar. Fow now I'm marking this as a wontfix.
