### ISSUE TITLE
favorite_color: 'Blue' is not in the repl dataset

### ISSUE THREAD

**Issue by Hoxolotl** [muze-nl/jaqt#7]
favorite_color: 'Blue' is not in the dataset:

On https://github.com/muze-nl/jaqt/blob/main/docs/manual.md it states:

```javascript
You can match people with 'Blue' among their favorite colors like this:

result = from(data)
.where({
    favorite_color: 'Blue'
})
.select({
    name: _
})
```

looking at the repl/data.json, this data is not in the dataset.

**Comment by poef** [comment]
That is correct, happy to accept patches :)
